### ISSUE TITLE
Alias struct methods

### ISSUE THREAD

**Issue by orien** [notahat/finer_struct#11]
Prior to version 0.0.6 one could alias methods defined via FinerStruct like so:

```ruby
class MyStruct < FinerStruct::Immutable(:nice)
  alias_method(:nice?, :nice)
end

instance = MyStruct.new(nice: true)
instance.nice? # => true
```

In 0.0.6 `alias_method` no longer works. It instead raises an error.
```
NameError: undefined method `nice' for class `MyStruct'
```

It seems the struct methods are no longer available via the class, rather are created during instantiation.

It would be great to have these methods available at the class level and get this feature back.

**Comment by notahat** [comment]
@orien Can you test https://github.com/notahat/finer_struct/pull/14 and see if it helps?
